import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Inserir os usuários
  await prisma.user.createMany({
    data: [
      {
        id: 1,
        email: 'vitoriatutor@gmail.com',
        password: 'tutorvitoria',
        name: 'Vitória Oliveira',
        phone: '21987654321',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de História com foco em História do Brasil e História da América Latina. Apaixonada por ensinar e aprender sobre os diferentes períodos históricos.',
        seen: false,
        availability: 6,
        location: 'Porto Alegre-RS',
      },
      {
        id: 2,
        email: 'camilatutor@gmail.com',
        password: 'tutorcamila',
        name: 'Camila Silva',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Química com especialização em Química Orgânica e Síntese de Materiais. Fascinada pela composição molecular e suas aplicações práticas.',
        seen: false,
        availability: 5,
        location: 'Salvador-BA',
      },
      {
        id: 3,
        email: 'luistutor@gmail.com',
        password: 'tutorluiz',
        name: 'Luís Oliveira',
        phone: '21912345678',
        role: true,
        degree: 'Nível Superior',
        description: 'Professor de Física com ênfase em Física Teórica e Física de Partículas. Interessado em compreender os fundamentos do universo e suas leis.',
        seen: false,
        availability: 7,
        location: 'Recife-PE',
      },
      {
        id: 4,
        email: 'carlostutor@gmail.com',
        password: 'tutorcarlos',
        name: 'Carlos Santos',
        phone: '21987654321',
        role: true,
        degree: 'Nível Superior',
        description: 'Professor de Biologia com foco em Ecologia e Conservação Ambiental. Comprometido em promover a conscientização sobre a importância da preservação da natureza.',
        seen: false,
        availability: 6,
        location: 'Belo Horizonte-MG',
      },
      {
        id: 5,
        email: 'fernandatutor2@gmail.com',
        password: 'tutorfernanda2',
        name: 'Fernanda Almeida',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Inglês como Segunda Língua (ESL) com foco em Conversação e Cultura. Interessada em ajudar os alunos a desenvolverem habilidades comunicativas e culturais.',
        seen: false,
        availability: 5,
        location: 'São Paulo-SP',
      },
      {
        id: 6,
        email: 'luisatutor@gmail.com',
        password: 'tutorluisa',
        name: 'Luísa Ferreira',
        phone: '21912345678',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Língua Portuguesa e Literatura, com experiência em redação e gramática. Acredita na importância da comunicação eficaz e da apreciação da literatura.',
        seen: false,
        availability: 6,
        location: 'Salvador-BA',
      },
      {
        id: 7,
        email: 'raqueltutor@gmail.com',
        password: 'tutorraquel',
        name: 'Raquel Almeida',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Geografia com especialização em Geopolítica e Geografia Humana. Apaixonada por explorar os aspectos culturais e políticos do mundo.',
        seen: false,
        availability: 5,
        location: 'Recife-PE',
      },
      {
        id: 8,
        email: 'lucastutor@gmail.com',
        password: 'tutorlucas',
        name: 'Lucas Santos',
        phone: '21987654321',
        role: true,
        degree: 'Nível Superior',
        description: 'Professor de Biologia com foco em Zoologia e Ecologia. Apaixonado por explorar a diversidade da vida e seus ecossistemas.',
        seen: false,
        availability: 6,
        location: 'Belo Horizonte-MG',
      },
      {
        id: 9,
        email: 'marinatutor@gmail.com',
        password: 'tutormarina',
        name: 'Marina Oliveira',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Física com ênfase em Física Moderna e Cosmologia. Fascinada pelos mistérios do universo e suas leis fundamentais.',
        seen: false,
        availability: 5,
        location: 'São Paulo-SP',
      },
      {
        id: 10,
        email: 'danielatutor@gmail.com',
        password: 'tutordaniela',
        name: 'Daniela Lima',
        phone: '21987654321',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Química com especialização em Química Orgânica e Química Farmacêutica. Interessada em aplicar os princípios químicos na área da saúde.',
        seen: false,
        availability: 6,
        location: 'Rio de Janeiro-RJ',
      },
      {
        id: 11,
        email: 'lucianatutor@gmail.com',
        password: 'tutorluciana',
        name: 'Luciana Silva',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de Inglês como Segunda Língua (ESL) com ênfase em Ensino para Negócios. Focada em preparar os alunos para desafios profissionais.',
        seen: false,
        availability: 5,
        location: 'Brasília-DF',
      },
      {
        id: 12,
        email: 'fernandotutor@gmail.com',
        password: 'tutorfernando',
        name: 'Fernando Santos',
        phone: '21987654321',
        role: true,
        degree: 'Nível Superior',
        description: 'Professor de Matemática com especialização em Álgebra e Geometria. Comprometido em ensinar os conceitos fundamentais de forma clara e acessível.',
        seen: false,
        availability: 6,
        location: 'Belo Horizonte-MG',
      },
      {
        id: 13,
        email: 'luciatutor@gmail.com',
        password: 'tutorlucia',
        name: 'Lúcia Oliveira',
        phone: '21912345678',
        role: true,
        degree: 'Nível Superior',
        description: 'Professora de História com especialização em História Antiga e Medieval. Apaixonada por explorar os mistérios das civilizações antigas.',
        seen: false,
        availability: 7,
        location: 'Curitiba-PR',
      },
      {
        id: 14,
        email: 'marcos@tutor@gmail.com',
        password: 'tutormarcos',
        name: 'Marcos Oliveira',
        phone: '21876543210',
        role: true,
        degree: 'Nível Superior',
        description: 'Professor de Geografia com foco em Geografia Física e Geomorfologia. Interessado em compreender os processos naturais que moldam o nosso planeta.',
        seen: false,
        availability: 5,
        location: 'Porto Alegre-RS',
      },
    ],
  });

  // Inserir os interesses
  await prisma.interest.createMany({
    data: [
      { userId: 1, name: 'História do Brasil' },
      { userId: 1, name: 'História da América Latina' },
      { userId: 1, name: 'Colonização Portuguesa' },
      { userId: 1, name: 'Independência do Brasil' },
      { userId: 1, name: 'Era Vargas' },
      { userId: 1, name: 'Ditadura Militar' },
      { userId: 1, name: 'Revolução Mexicana' },
      { userId: 1, name: 'Guerra do Paraguai' },
      { userId: 1, name: 'Escravidão no Brasil' },
      { userId: 1, name: 'Imperialismo' },
      { userId: 2, name: 'Química Orgânica' },
      { userId: 2, name: 'Síntese de Materiais' },
      { userId: 2, name: 'Espectroscopia' },
      { userId: 2, name: 'Cromatografia' },
      { userId: 2, name: 'Química Ambiental' },
      { userId: 3, name: 'Física Teórica' },
      { userId: 3, name: 'Física de Partículas' },
      { userId: 3, name: 'Astrofísica' },
      { userId: 3, name: 'Relatividade' },
      { userId: 3, name: 'Mecânica Quântica' },
      { userId: 4, name: 'Ecologia' },
      { userId: 4, name: 'Conservação Ambiental' },
      { userId: 4, name: 'Biodiversidade' },
      { userId: 4, name: 'Biologia Marinha' },
      { userId: 4, name: 'Biologia de Campo' },
      { userId: 5, name: 'Conversação em Inglês' },
      { userId: 5, name: 'Cultura Inglesa' },
      { userId: 5, name: 'Inglês para Negócios' },
      { userId: 5, name: 'Inglês Acadêmico' },
      { userId: 5, name: 'Preparação para Exames' },
      { userId: 6, name: 'Gramática' },
      { userId: 6, name: 'Redação' },
      { userId: 6, name: 'Literatura Brasileira' },
      { userId: 6, name: 'Literatura Portuguesa' },
      { userId: 6, name: 'Linguística' },
      { userId: 7, name: 'Geopolítica' },
      { userId: 7, name: 'Geografia Humana' },
      { userId: 7, name: 'Cartografia' },
      { userId: 7, name: 'Geografia Urbana' },
      { userId: 7, name: 'Geografia Econômica' },
      { userId: 8, name: 'Zoologia' },
      { userId: 8, name: 'Ecologia' },
      { userId: 8, name: 'Biologia Evolutiva' },
      { userId: 8, name: 'Genética' },
      { userId: 8, name: 'Biologia de Campo' },
      { userId: 9, name: 'Física Moderna' },
      { userId: 9, name: 'Cosmologia' },
      { userId: 9, name: 'Astrofísica' },
      { userId: 9, name: 'Relatividade' },
      { userId: 9, name: 'Mecânica Quântica' },
      { userId: 10, name: 'Química Orgânica' },
      { userId: 10, name: 'Química Farmacêutica' },
      { userId: 10, name: 'Bioquímica' },
      { userId: 10, name: 'Análise Instrumental' },
      { userId: 10, name: 'Química Ambiental' },
      { userId: 11, name: 'Inglês para Negócios' },
      { userId: 11, name: 'Preparação para Entrevistas' },
      { userId: 11, name: 'Comunicação Empresarial' },
      { userId: 11, name: 'Redação Profissional' },
      { userId: 11, name: 'Apresentações em Inglês' },
      { userId: 12, name: 'Álgebra' },
      { userId: 12, name: 'Geometria' },
      { userId: 12, name: 'Trigonometria' },
      { userId: 12, name: 'Cálculo' },
      { userId: 12, name: 'Estatística' },
      { userId: 13, name: 'História Antiga' },
      { userId: 13, name: 'História Medieval' },
      { userId: 13, name: 'Arqueologia' },
      { userId: 13, name: 'Mitologia' },
      { userId: 13, name: 'História das Religiões' },
      { userId: 14, name: 'Geografia Física' },
      { userId: 14, name: 'Geomorfologia' },
      { userId: 14, name: 'Climatologia' },
      { userId: 14, name: 'Hidrologia' },
      { userId: 14, name: 'Geologia' },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
